-- AUTHOR:		SOK KIM THANH
-- CREATE DATE: <17/12/2023>
-- UPDATE DATE 6:44 CH
DROP PROCEDURE IF EXISTS sp_sanpham_phantrang_count
GO
CREATE PROCEDURE sp_sanpham_phantrang_count
    @LOAISANPHAM NVARCHAR(100) = NULL,
    @NHACUNGCAP NVARCHAR(100) = NULL,
    @SEARCHTERM NVARCHAR(100) = NULL
AS
BEGIN 
    -- LẤY DỮ LIỆU VÀ CHỈ SỐ DÒNG (ROW) CỦA NÓ
    WITH PHANTRANG AS (
        SELECT ROW_NUMBER() OVER (ORDER BY SP.MASP) AS STT
            ,SP.MASP, SP.TENSP, SP.DONVI, SP.DONGIA
            ,KM.PHANTRAMGIAMGIA  AS GIAMGIA
	        ,DONGIA * (100- KM.PHANTRAMGIAMGIA)/100 AS GIABAN
            ,SLTONKHO
        FROM SANPHAM SP
        INNER JOIN KHUYENMAI KM ON SP.MAKM = KM.MAKM
        WHERE TENSP LIKE '%' + ISNULL(@SEARCHTERM, TENSP) + '%'
        AND MALOAI = ISNULL(@LOAISANPHAM, MALOAI)
        AND MANCC = ISNULL(@NHACUNGCAP, MANCC) AND SLTONKHO > 0
    )
    -- ĐẾM SỐ DÒNG
    SELECT COUNT(*) AS TOTALROWS
    FROM PHANTRANG;
END;
GO
EXECUTE SP_SANPHAM_PHANTRANG_COUNT NULL,NULL,'F'
